//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Authentication.ActiveDirectory
{
    public partial class Settings
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Image Image1;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.HtmlControls.HtmlTable tblSettings;
        protected global::System.Web.UI.HtmlControls.HtmlTableCell MessageCell;
        protected global::DotNetNuke.UI.UserControls.LabelControl plAuthentication;
        protected global::System.Web.UI.WebControls.CheckBox chkAuthentication;
        protected global::DotNetNuke.UI.UserControls.LabelControl plHidden;
        protected global::System.Web.UI.WebControls.CheckBox chkHidden;
        protected global::DotNetNuke.UI.UserControls.LabelControl plSynchronizeRole;
        protected global::System.Web.UI.WebControls.CheckBox chkSynchronizeRole;
        protected global::DotNetNuke.UI.UserControls.LabelControl plSynchronizePhoto;
        protected global::System.Web.UI.WebControls.CheckBox chkSynchronizePhoto;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowSynchornizePassword;
        protected global::DotNetNuke.UI.UserControls.LabelControl plSynchornizePassword;
        protected global::System.Web.UI.WebControls.CheckBox chkSynchronizePassword;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowAutoCreate;
        protected global::DotNetNuke.UI.UserControls.LabelControl plAutoCreate;
        protected global::System.Web.UI.WebControls.CheckBox chkAutoCreate;
        protected global::DotNetNuke.UI.UserControls.LabelControl plStripDomainName;
        protected global::System.Web.UI.WebControls.CheckBox chkStripDomainName;
        protected global::DotNetNuke.UI.UserControls.LabelControl plProvider;
        protected global::System.Web.UI.WebControls.DropDownList cboProviders;
        protected global::DotNetNuke.UI.UserControls.LabelControl plAuthenticationType;
        protected global::System.Web.UI.WebControls.DropDownList cboAuthenticationType;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowRootDomain;
        protected global::DotNetNuke.UI.UserControls.LabelControl plRootDomain;
        protected global::System.Web.UI.WebControls.TextBox txtRootDomain;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowUserName;
        protected global::DotNetNuke.UI.UserControls.LabelControl plUserName;
        protected global::System.Web.UI.WebControls.TextBox txtUserName;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowPassword;
        protected global::DotNetNuke.UI.UserControls.LabelControl plPassword;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowConfirm;
        protected global::DotNetNuke.UI.UserControls.LabelControl plConfirm;
        protected global::System.Web.UI.WebControls.TextBox txtConfirm;
        protected global::System.Web.UI.WebControls.CompareValidator valConfirm;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowEmailDomain;
        protected global::DotNetNuke.UI.UserControls.LabelControl plEmailDomain;
        protected global::System.Web.UI.WebControls.TextBox txtEmailDomain;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowDefaultDomain;
        protected global::DotNetNuke.UI.UserControls.LabelControl plDefaultDomain;
        protected global::System.Web.UI.WebControls.TextBox txtDefaultDomain;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowSubNet;
        protected global::DotNetNuke.UI.UserControls.LabelControl plAutoIP;
        protected global::System.Web.UI.WebControls.TextBox txtAutoIP;
        protected global::System.Web.UI.HtmlControls.HtmlTableRow rowBots;
        protected global::DotNetNuke.UI.UserControls.LabelControl plBots;
        protected global::System.Web.UI.WebControls.TextBox txtBots;
    }
}
